---


- name: 客户端远程连接数据库
  #shell: mysql -uroot -p"{{ root_password }}" -e "GRANT ALL PRIVILEGES ON *.* TO '{{ wduser_user }}'@'%'IDENTIFIED BY '{{ wduser_password }}' WITH GRANT OPTION;"

  mysql_user:
    login_password: "{{ root_password }}"
    login_user: root
    name: "{{ wduser_user }}"
    password: "{{ wduser_password }}"
    host: '%' 
    login_unix_socket: "{{ mysql_socket }}"
    priv: "*.*:ALL"
    state: present

